services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: case_pp-api:local
    container_name: case_pp-api
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --no-access-log
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: dev
      DEBUG: "true"
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: case_pp
    depends_on:
      - mongo
    volumes:
      - ./app:/code/app

  mongo:
    image: mongo:7
    container_name: case_pp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
